# docker build -t brennoli/project_2_djl-serving:0.19.0 .
# docker push brennoli/project_2_djl-serving:0.19.0

# TODO later versions not working
FROM deepjavalibrary/djl-serving:0.19.0

# Copy Model
COPY *.zip /opt/ml/model/

